#!/bin/sh
# execute: ./W_electr

#cd /home/ahnac/Compiler/Njoy2012_EPM_cepxsr
#./install
#cd /home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/electron_proc


echo "**********************************************************"
echo "           Construt NJOY files                            "
echo "**********************************************************"

System=`uname -s`

FolderNjoy=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/electron_proc/electr/;
FolderDragonData=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data;
cd $FolderNjoy;
rm tape*


Ne=$1;
Ng=$2;
Legendre=$3;
Nmat=2;
Emin=$4; Emax=$5; 

Title="W-electr:non-coupled";
FileExtension="electr_W300g_20MeV_nc.txt"
FileInPut="in_${FileExtension}";
FileOutPut="out_${FileExtension}";
FileGendf="gendf_${FileExtension}";
FileMatxs="matxs_${FileExtension}";

HOME=/home/ahnac/Compiler/;
echo "--------------------------------------------------";
echo "       1- Access ENDF-B.VIII data                 ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/evaluations/ENDF-B-VIII.0/electrons/EEDL2017.ALL.txt tape30
ln -s /home/ahnac/Compiler/evaluations/ENDF-B-VIII.0/atomic_relax/EADL2017.ALL.txt tape39


echo "--------------------------------------------------";
echo "       2- Access STOPPING POWER data              ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/Njoy2012_EPM_cepxsr/STPOWER_TAPE9_1984.txt tape38

echo "--------------------------------------------------";
echo "       3- NJOY is operating                       ";
echo "--------------------------------------------------";



weight_function_option=2;
iprint=1;

cat>./input <<EOF
 reconr
 30 31
 'pendf tape for electron interaction cross sections from EPICS2017'/
 7400 1 0
 .001/
 'tungsten'/
 0/
 electr
 30 31 38 39 0 33
 7400 3 0 2 2 1
 $Title/
 -1 0/
 0/
-- matxsr
-- 0  0 35  0  0  0  0  0  0 33/ 
-- 1 'test'/                     
-- 1 1 1 1 /                   
-- 'test'/
-- 'b'/
-- 300/
-- 'bscat'/
-- 1
-- 1
-- 'w' 7400 7400  
stop
EOF

/home/ahnac/Compiler/Njoy2012_EPM_cepxsr/Linux/xnjoy<input

echo "--------------------------------------------------";
echo "      4- Saving output and plot files             ";
echo "--------------------------------------------------";

mv input  $FileInPut
mv output $FileOutPut
mv tape33 $FileGendf
mv tape35 $FileMatxs

echo "--------------------------------------------------";
echo "      5- Input file removed                       ";
echo "--------------------------------------------------";

#ls -t | head -n4;

#echo "**********************************************************"
#echo "           Dragon .access file construction               "
#echo "**********************************************************"

#file_access_dragon='/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/electron.access' 
#sed  -i "/#--- CEPXSR-NJOY/a  ln -s \$1/data/cepxs-dragon/$fmac_file_name_ascii ." $file_access_dragon 

# echo "--------------------------------------------------";
# echo "      Execute DRAGON                              ";
# echo "--------------------------------------------------";
# 
# cd /home/ahnac/Compiler/dragon5_ev2148_2/Dragon
# ./rdragon electron.x2m
