#!/bin/sh
#
# author : A. Hebert
# use    : rskin [<compiler>] [-w]
#          <compiler> is the compiler used to generate the executable
#          -w     to execute in console
#          -quiet quiet execution for regression testing
#
System=`uname -s`
Sysx="`echo $System | cut -b -6`"
if [ $Sysx = "CYGWIN" ]; then
   MACH=`uname -o`
elif [ $Sysx = "AIX" ]; then
   MACH=`uname -s`
else
   MACH=`uname -sm | sed 's/[ ]/_/'`
fi

term=0
quiet=0
log=0
typ='custom'

for param in $*
do
   case $param in
      -w) echo Execute in terminal
          term=1
          ;;
      -quiet)
          quiet=1
          ;;
      *) if [ $log = 0 ]; then
            typ=$param
         fi ;;
   esac
done
Code=`basename "$PWD"`
if [ $quiet = 0 ]; then
  echo 'execute with' $Code 'on system' $MACH 'with' $typ 'compiler'
fi

if [ -d "$MACH" ]; then
  if [ $quiet = 0 ]; then
  echo 'use the existing directory' $MACH
  fi
else
  echo 'creation of directory' $MACH
  mkdir "$MACH"
fi
CodeDir=$PWD

if [ $Sysx = "AIX" ]; then
  Tmpdir=/usr/tmp
elif [ $Sysx = "SunOS" ]; then
  Tmpdir=/var/tmp
else
  Tmpdir=/tmp
fi
inum=1
while [ -d $Tmpdir/rundir$inum ]
  do
  inum=`expr $inum + 1 `
done
Rundir=$Tmpdir/rundir$inum
mkdir $Rundir
if [ $quiet = 0 ]; then
  echo "RunDirectory:" $Rundir
fi
cd $Rundir

if [ $typ = 'custom' ]; then
  cp "$CodeDir"/bin/"$MACH"/$Code ./code
else
  cp "$CodeDir"/bin/"$MACH"'_'$typ/$Code ./code
fi

ln -s "$CodeDir"/data/* .

before=$(date +%s)
if [ $term = 0 ]; then
  ./code >result
else
  ./code
fi
if [ $quiet = 0 ]; then
  time=$(( $(date +%s) - before))
  printf 'End of execution. Total execution time: %dh %dmin %ds\n' \
    $(($time/3600)) $(($time%3600/60)) $(($time%60))
fi
mv result "$CodeDir"/"$MACH"
if [ $quiet = 0 ]; then
  echo 'the listing is located on ./'$MACH
fi

cd "$CodeDir"/"$MACH"
if [ $quiet = 0 ]; then
  tail -25 result
else
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  if tail result | grep -q "normal end" ; then
    printf "${GREEN}[OK]${NC}\n"
  else
    printf "${RED}[FAILED]${NC}\n"
  fi
fi
chmod -R 777 $Rundir
/bin/rm -r -f $Rundir
cd ..
