#!/bin/sh

# execute: ./water_cepxsr Ne Ng Pl  Emin_eV Emax_eV 
# e.g.: ./test 12 12 8 

echo "**********************************************************"
echo "           Construt NJOY files                            "
echo "**********************************************************"

System=`uname -s`

FolderNjoy=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/cepxsr-dragon/njoy;
FolderDragonData=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data;
cd $FolderNjoy;
rm tape*


Ne=$1;
Ng=$2;
Legendre=$3;
Nmat=2;
Emin=$4; Emax=$5; 

Title="water-electron-library-P${Legendre}-${Ne}Ne-${Ng}Ng";
FileExtension="test_lanl_cepxsr_${Ne}Ne_${Ng}Ng.txt"
FileInPut="in_${FileExtension}";
FileOutPut="out_${FileExtension}";
FileGendf="gendf_${FileExtension}";
FileMatxs="matxs_${FileExtension}";


echo "--------------------------------------------------";
echo "       1- Access ENDF-B-VIII data                 ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/evaluations/ENDF-B-VIII.0/electrons/EEDL2017.ALL.txt tape30


echo "--------------------------------------------------";
echo "       2- Access CEPXS-BFP data                   ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/Njoy2012_EPM_cepxsr/TAPE9 tape40

echo "--------------------------------------------------";
echo "       3- NJOY is operating                       ";
echo "--------------------------------------------------";

#--------------------------------------------------------
# CEPXSR input file: 
#--------------------------------------------------------
if [[ $Ng == 0 ]] ; then
    group_structure_e=-2; group_structure_g=0;
    GroupsLimits="$Ne $Emin $Emax";
	npart=1;
	ndata_type=1;
    part_iden_1='b';
	part_iden_2='/';
	Ng='/';
	data_type1='bscat';
	data_type2='bgamma /'; #'/';
	input_particle_id_data1=1;
    input_particle_id_data2=1 #'';
    output_particle_id_data1=1;
    output_particle_id_data2='';
else
	group_structure_e=-2; group_structure_g=-2; 
GroupsLimits="$Ne $Emin $Emax
 $Ng $Emin $Emax";
	npart=2;      #number of particles
	ndata_type=2; #number of data types in set
    part_iden_1='b';
	part_iden_2='g';
	data_type1='bscat';
	data_type2='bgamma';
	input_particle_id_data1=1;
    input_particle_id_data2=1;
    output_particle_id_data1=1;
    output_particle_id_data2=2;
fi  

weight_function_option=2;
iprint=1;
cat>./input <<EOF
cepxsr
 30 0 33 40
 100 3 3 $weight_function_option $Legendre $iprint
 $Title/
 -1 0/
 800
 -1 0/
 0/
matxsr
 0  0 35  0  0  0  0  0  0 33/
 1 'cepxsr-njoy'/
 $npart $ndata_type 1 $Nmat
 $Title/
 '$part_iden_1' '$part_iden_2'/
 12 12
 '$data_type1' '$data_type2'/
 $input_particle_id_data1 $input_particle_id_data2
 $output_particle_id_data1 $output_particle_id_data2
 'h' 100 100
 'o' 800 800  
-- ---------------------------------------------------------
--                       END NJOY                         --
-- --------------------------------------------------------- 
 stop
EOF


/home/ahnac/Compiler/Njoy2012_EPM_cepxsr/Linux/xnjoy<input

echo "--------------------------------------------------";
echo "      4- Saving output and plot files             ";
echo "--------------------------------------------------";

mv input  $FileInPut
mv output $FileOutPut
mv tape33 $FileGendf
mv tape35 $FileMatxs

#mv $FileMatxs /home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/cepxsr-dragon/$FileMatxs
#ln -s /home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/cepxsr-dragon/$FileMatxs $FileMatxs
echo "--------------------------------------------------";
echo "      5- Input file removed                       ";
echo "--------------------------------------------------";

ls -t | head -n4;

echo "**********************************************************"
echo "           Dragon .access file construction               "
echo "**********************************************************"

#cd .. ; #exit njoy folder 

#cd $FolderDragonData;

#file_access_dragon='/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/water_1D.access' 

#sed  -i "/#--- CEPXSR-NJOY/a  ln -s \$1/data/cepxsr-dragon/njoy/$FileMatxs _cepxsr_P${Legendre}_${Ne}Ne_${Ng}Ng" $file_access_dragon 
