#!/bin/sh
# --- MANUAL ENERGY GROUP SELECTION 
# execute: ./water_debug
# e.g.: ./water_debug

echo "**********************************************************"
echo "           Construt NJOY files                            "
echo "**********************************************************"

System=`uname -s`

FolderNjoy=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/cepxsr-dragon/njoy/test/;
FolderDragonData=/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data;
cd $FolderNjoy;
rm tape*


Ne=$1;
Ng=$2;
Legendre=$3;
Nmat=2;
Emin=$4; Emax=$5; 

Title="test";
FileExtension="test.txt"
FileInPut="in_${FileExtension}";
FileOutPut="out_${FileExtension}";
FileGendf="gendf_${FileExtension}";
FileMatxs="matxs_${FileExtension}";

HOME=/home/ahnac/Compiler/;
echo "--------------------------------------------------";
echo "       1- Access ENDF-B.VIII data                 ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/evaluations/ENDF-B-VIII.0/electrons/EEDL2017.ALL.txt tape30

echo "--------------------------------------------------";
echo "       2- Access CEPXS-BFP data                   ";
echo "--------------------------------------------------";

ln -s /home/ahnac/Compiler/Njoy2012_EPM_cepxsr/TAPE9 tape40
ln -s /home/ahnac/Compiler/Njoy2012_EPM_cepxsr/STPOWER_TAPE9_1984.txt tape38
ln -s /home/ahnac/Compiler/evaluations/ENDF-B-VIII.0/atomic_relax/EADL2017.ALL.txt tape39

echo "--------------------------------------------------";
echo "       3- NJOY is operating                       ";
echo "--------------------------------------------------";



weight_function_option=2;
iprint=1;

cat>./input <<EOF
cepxsr
30 0 33 40 
100 1 0 2 2 1
$Title/
2 / # of groups, electron energy boundaries follow:
1.00000E+03 2.00033E+06 3.99967E+06 /
-1 0/
800
-1 0/
0/
matxsr
0  0 35  0  0  0  0  0  0 33/
1 'test'/
1 1 1 2
'test'/
'b'/
2/
'bscat'/
1
1
'h' 100 100
'o' 800 800
stop
-- 30 0 33 40 
-- 100 1 1 2 2 1
-- $Title/
-- 2 / # of groups, electron energy boundaries follow:
-- 1.00000E+03 2.00033E+06 3.99967E+06 /
-- 2 / # of groups, photon energy boundaries follow:
-- 1.00000E+03 2.00033E+06 3.99967E+06 /
-- -1 0/
-- 800
-- -1 0/
-- 0/
-- matxsr
-- 0  0 35  0  0  0  0  0  0 33/
-- 1 'test'/
-- 2 2 1 2
-- 'test'/
-- 'b' 'g' /
-- 2 2 /
-- 'bscat' 'bgamma' /
-- 1 1
-- 1 2
-- 'h' 100 100
-- 'o' 800 800
-- stop
EOF
#cat>./input <<EOF
#cepxsr
# 30 0 33 40 
# 100 1 0 2 5 1
# $Title/
# 12 1.0E+3 2.0E+3 3.0E+3 4.0E+3 5.0E+3 6.0E+3 7.0E+3 8.0E+3 9.0E+3 10.0E+3 11.0E+3 12.0E+3 13.0E+3 /
# -1 0/
# 0/
# stop
#EOF

# matxsr
# 0  0 35  0  0  0  0  0  0 33/
# 1 'test'/
# 1 1 1 1
# 'test'/
# 'b' /
# 80 /
# 'bscat'/
# 1
# 1
# 'w' 7400 7400
/home/ahnac/Compiler/Njoy2012_EPM_cepxsr/Linux/xnjoy<input

echo "--------------------------------------------------";
echo "      4- Saving output and plot files             ";
echo "--------------------------------------------------";

mv input  $FileInPut
mv output $FileOutPut
mv tape33 $FileGendf
mv tape35 $FileMatxs

echo "--------------------------------------------------";
echo "      5- Input file removed                       ";
echo "--------------------------------------------------";

#ls -t | head -n4;

#echo "**********************************************************"
#echo "           Dragon .access file construction               "
#echo "**********************************************************"


#cd $FolderDragonData;

#file_access_dragon='/home/ahnac/Compiler/dragon5_ev2148_2/Dragon/data/water_1D.access' 

#sed  -i "/#--- CEPXSR-NJOY/a  ln -s \$1/data/cepxsr-dragon/njoy/$FileMatxs _cepxsr_P${Legendre}_${Ne}Ne_${Ng}Ng" $file_access_dragon 
